export const TEST_NAME = {
  script: "LATIN",
  id: "76d53c84-623b-4e8c-9414-3e68b9b1d171",
  firstName: "Aiman",
  lastName: "unset",
  meaning: "right-handed, blessed, lucky",
  countryOrigin: "Kazakhstan",
  countryOriginAlt: "Saudi Arabia",
  countriesOriginTop: [
    "KZ",
    "SA",
    "AF",
    "BN",
    "MY",
    "PK",
    "AZ",
    "EG",
    "MA",
    "SY",
  ],
  score: 6.51,
  regionOrigin: "Asia",
  topRegionOrigin: "Asia",
  subRegionOrigin: "Central Asia",
  probabilityCalibrated: 0.66,
  probabilityAltCalibrated: 0.7051,
};
